name: On main

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "**.txt"
      - "docs/**"

jobs:
  ci:
    uses: laenen-partners/gh-action-scripts/.github/workflows/ci.yaml@main
    with:
      upload-artifacts: true

  release:
    needs: ci
    uses: laenen-partners/gh-action-scripts/.github/workflows/release.yaml@main
    permissions:
      contents: write
