name: On Weekly

on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  upgrade:
    uses: laenen-partners/gh-action-scripts/.github/workflows/upgrade-tools.yaml@main
